[package]
name = "palindromes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethnum = "1.1.1"
rayon = "1.5.1"
hashbrown = "0.12.0"
once_cell = "1.10.0"
