[package]
name = "palindromes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethnum = "1.3.2"
rayon = "1.6.1"
once_cell = "1.17.1"
sysinfo = "0.28.1"
